-- ============================================================
-- Meraki App — Parte 2: Contenido (zonas, niveles, pasos,
-- estiramientos y masajes en pareja). Generado automáticamente
-- desde js/zonas.js, js/estiramientos.js y js/pareja.js.
-- ============================================================

-- ---------- BLOQUE 2.1 — ZONAS Y NIVELES ----------

insert into public.zonas (id, nombre, bloque, premium, categoria_emocional, por_que, dato_clinico, evitar_si, orden) values
('trapecio', 'Trapecio', 'Cuello y cabeza', false, true, 'Pasar horas con la cabeza inclinada hacia adelante (celular, computadora) o con los hombros subidos por estrés satura este músculo, que va desde el cráneo hasta la mitad de la espalda. También es la zona clásica donde "guardamos" el estrés: el insomnio, la ansiedad o una época difícil pueden tensarla tanto como una mala postura.', 'Es uno de los músculos que más se contractura en el cuerpo, y su punto de tensión puede generar dolor de cabeza de tipo tensional que sube desde el cuello hacia la sien.', 'Hinchazón marcada, calor o enrojecimiento en la zona; dolor que baja disparado hacia el brazo.', 1),
('suboccipital', 'Suboccipital / Nuca', 'Cuello y cabeza', true, true, 'Son músculos pequeños que sostienen la cabeza en posiciones finas. Mirar el celular hacia abajo o el estrés los acorta y tensiona. El estrés sostenido y la falta de sueño también los contraen, incluso sin una causa postural clara — muchas cefaleas tensionales aparecen así.', 'Generan un patrón de dolor referido muy característico: empieza en la nuca y sube hacia la frente o las sienes, muy similar a una cefalea tensional.', 'Mareo al presionar, dolor que se dispara con la presión, cualquier golpe reciente en la zona.', 2),
('temporal', 'Cuero cabelludo / sien (temporal)', 'Cuello y cabeza', true, false, 'El músculo temporal, en el costado de la cabeza, ayuda a cerrar la mandíbula. Se sobrecarga por apretar los dientes o por tensión general del estrés.', 'Los dolores de cabeza tipo "banda de presión" en el costado de la cabeza suelen originarse en el temporal, no en el cuero cabelludo como tal.', 'Heridas o infecciones en el cuero cabelludo, dolor de cabeza súbito y muy intenso (requiere evaluación médica).', 3),
('mandibula', 'Mandíbula (ATM / masetero)', 'Cuello y cabeza', true, true, 'El estrés y el bruxismo (apretar o rechinar los dientes) sobrecargan el masetero, el músculo principal para cerrar la mandíbula. El bruxismo casi siempre tiene una raíz emocional: ansiedad, estrés acumulado o una etapa de mucha exigencia personal.', 'El automasaje no alcanza los músculos más profundos de la mandíbula, por eso si hay chasquidos, bloqueos o dolor fuerte al abrir la boca, se necesita evaluación profesional.', 'Chasquidos o bloqueo al abrir la boca, dolor dental agudo, cirugía dental reciente.', 4),
('hombro', 'Hombro (deltoides)', 'Espalda', true, false, 'Los deltoides rodean la articulación del hombro y se sobrecargan al cargar peso o mantener los brazos elevados mucho tiempo.', 'Trabajar el deltoides de forma longitudinal y lento reduce la hiperactividad muscular y calma las señales de dolor.', 'Hombro congelado diagnosticado, luxación reciente, dolor agudo al levantar el brazo.', 5),
('omoplatos', 'Omóplatos (romboides / escápula)', 'Espalda', true, false, 'Es la zona típica de "cargar la mochila del estrés" — se tensiona por mantener los hombros hacia adelante frente a la computadora.', 'Trabajar esta zona con las manos ayuda a liberar también estructuras cercanas al manguito rotador, mejorando la movilidad del hombro.', 'Nunca presionar directo sobre el borde óseo de la escápula, solo sobre el músculo.', 6),
('dorsal', 'Dorsal / zona alta de la espalda', 'Espalda', true, false, 'Las horas de mala postura frente a la pantalla cargan esta zona ancha de la espalda, que conecta el hombro con la zona lumbar.', 'El automasaje de esta zona alcanza el redondo mayor y el dorsal ancho — trabajar despacio y profundo con los nudillos da mayor beneficio que un pase rápido.', 'Dolor agudo tipo "punzada" al respirar hondo (puede ser otra causa, no muscular).', 7),
('lumbar', 'Lumbar (incluye cuadrado lumbar)', 'Espalda', false, true, 'Es de las zonas que más carga acumula por estar sentado muchas horas o cargar peso con mala postura. El cuadrado lumbar es el músculo detrás del típico "dolor de riñones". La tensión emocional sostenida (preocupación constante, ansiedad) también se acumula aquí, incluso sin haber cargado peso ni pasado horas sentada.', 'El automasaje lumbar se trabaja siempre a los lados de la columna (nunca sobre ella), con movimientos lentos, entre 3 y 6 minutos por lado.', 'Dolor que baja como un rayo hacia la pierna (posible compromiso del nervio ciático) — ahí no se automasajea, se consulta primero.', 8),
('piriforme', 'Glúteo / Piriforme', 'Cadera y glúteo', false, false, 'El piriforme es un músculo pequeño y profundo del glúteo. Al contracturarse, puede atrapar el nervio ciático.', 'Genera un patrón de dolor referido hacia la pierna muy parecido al de una hernia discal, sin serlo — se le conoce como "falsa ciática".', 'Dolor punzante y agudo al presionar (bajar la intensidad de inmediato), hernia discal sin autorización médica.', 9),
('pantorrillas', 'Pantorrillas', 'Piernas y pies', false, false, 'Estar mucho tiempo de pie o sentado hace que la circulación de retorno trabaje peor, y la pantorrilla es el músculo que más ayuda a bombear la sangre de vuelta al corazón.', 'Por esta función de bombeo se le conoce como "el segundo corazón" — trabajarla siempre en dirección ascendente ayuda a esa circulación de retorno.', 'Hinchazón marcada de un solo lado, calor local o dolor que no calza con cansancio normal — puede ser un tema circulatorio.', 10),
('planta_pie', 'Planta del pie', 'Piernas y pies', true, false, 'La fascia plantar sostiene el arco del pie y se sobrecarga por estar de pie muchas horas, calzado plano, o pantorrillas muy tensas.', 'Combinar el trabajo de la planta del pie con automasaje en la pantorrilla mejora el resultado, porque están conectadas.', 'Dolor agudo al primer paso de la mañana de forma repetida (trabajar con suavidad y consultar si no mejora).', 11),
('antebrazo', 'Antebrazo (extensores y flexores)', 'Brazo, antebrazo y mano', false, false, 'El uso de mouse y teclado sobrecarga el lado de arriba del antebrazo (extensores); escribir y cargar cosas sobrecarga el lado de abajo (flexores).', 'Cuando se inflama la inserción en el codo, del lado extensor es "codo de tenista" y del lado flexor es "codo de golfista" — son distintas y no se tratan igual.', 'Hormigueo, adormecimiento o "corrientazo" hacia los dedos (posible nervio comprometido).', 12),
('mano_muneca', 'Mano y muñeca', 'Brazo, antebrazo y mano', true, false, 'El uso constante del celular y el teclado sobrecarga los músculos pequeños de la palma y los dedos.', 'El hormigueo hacia pulgar/índice/medio puede indicar compromiso del nervio mediano en la muñeca — ahí no se automasajea, se consulta.', 'Hormigueo o adormecimiento hacia los dedos, hinchazón marcada en la muñeca.', 13),
('pectorales', 'Pectorales', 'Brazo, antebrazo y mano', true, false, 'Mantener los hombros hacia adelante frente a la pantalla tensiona y acorta este músculo.', 'Está muy relacionado con el dolor de hombro y la postura general — trabajarlo ayuda también a mejorar dolores cervicales.', 'Cualquier dolor en el pecho que no sea claramente muscular (opresión, falta de aire) requiere atención médica inmediata, no automasaje.', 14),
('abdomen', 'Abdomen', 'Brazo, antebrazo y mano', true, true, 'El estrés y estar sentado muchas horas afectan también el tránsito intestinal. Las emociones que se "guardan" sin procesar —ansiedad, preocupación, tristeza— afectan directamente la digestión: es una de las zonas donde el cuerpo somatiza de forma más clara.', 'El masaje abdominal es una herramienta real usada en fisioterapia para el estreñimiento, siguiendo el sentido del colon (como una "C" invertida), con presión suave.', 'Embarazo, dolor abdominal agudo, justo después de comer (esperar 1-2 horas), cualquier diagnóstico digestivo sin autorización médica.', 15);

insert into public.niveles_zona (id, zona_id, numero, dia_offset, titulo, avanzado, pregunta_extra, es_rutina_completa) values
(1,'trapecio',1,0,'Punto básico',false,false,false),
(2,'trapecio',2,3,'Borde lateral',false,false,false),
(3,'trapecio',3,7,'Punto medio',false,true,false),
(4,'trapecio',4,14,'Punto profundo',true,true,false),
(5,'trapecio',5,21,'Rutina completa',false,false,true),
(6,'suboccipital',1,0,'Borde óseo, primer contacto',false,false,false),
(7,'suboccipital',2,3,'Profundizando en el mismo borde',false,false,false),
(8,'suboccipital',3,7,'Punto lateral',false,true,false),
(9,'suboccipital',4,14,'Punto lateral, más profundo',true,true,false),
(10,'suboccipital',5,21,'Rutina completa (ambos lados)',false,false,true),
(11,'temporal',1,0,'Temporal, primer contacto',false,false,false),
(12,'temporal',2,3,'Profundizando en la sien',false,false,false),
(13,'temporal',3,7,'Punto posterior',false,true,false),
(14,'temporal',4,14,'Sien + mandíbula combinadas',true,true,false),
(15,'temporal',5,21,'Rutina completa (sien + mandíbula)',false,false,true),
(16,'mandibula',1,0,'Masetero superficial',false,false,false),
(17,'mandibula',2,3,'Masetero, más tiempo',false,false,false),
(18,'mandibula',3,7,'Masetero profundo',false,true,false),
(19,'mandibula',4,14,'Punto profundo en movimiento',true,true,false),
(20,'mandibula',5,21,'Rutina completa (superficial + profundo + sien)',false,false,true),
(21,'hombro',1,0,'Fibras externas y medias',false,false,false),
(22,'hombro',2,3,'Fibras medias, más tiempo',false,false,false),
(23,'hombro',3,7,'Fibras anteriores',false,true,false),
(24,'hombro',4,14,'Fibras posteriores',true,true,false),
(25,'hombro',5,21,'Rutina completa (3 porciones)',false,false,true),
(26,'omoplatos',1,0,'Borde interno',false,false,false),
(27,'omoplatos',2,3,'Borde interno, más presión',false,false,false),
(28,'omoplatos',3,7,'Punto superior',false,true,false),
(29,'omoplatos',4,14,'Elevador de la escápula',true,true,false),
(30,'omoplatos',5,21,'Rutina completa (ambos puntos)',false,false,true),
(31,'dorsal',1,0,'Primer contacto',false,false,false),
(32,'dorsal',2,3,'Profundizando',false,false,false),
(33,'dorsal',3,7,'Borde externo (cerca de la axila)',false,true,false),
(34,'dorsal',4,14,'Ángulo inferior del omóplato',true,true,false),
(35,'dorsal',5,21,'Rutina completa (3 puntos)',false,false,true),
(36,'lumbar',1,0,'A los lados de la columna',false,false,false),
(37,'lumbar',2,3,'Más tiempo por lado',false,false,false),
(38,'lumbar',3,7,'Punto cerca de la cadera',false,true,false),
(39,'lumbar',4,14,'Mismo punto, más profundo',true,true,false),
(40,'lumbar',5,21,'Rutina completa (ambos lados)',false,false,true),
(41,'piriforme',1,0,'Piriforme central',false,false,false),
(42,'piriforme',2,3,'Piriforme central, más tiempo',false,false,false),
(43,'piriforme',3,7,'Glúteo medio, punto alto',false,true,false),
(44,'piriforme',4,14,'Glúteo medio, punto medio',true,true,false),
(45,'piriforme',5,21,'Rutina completa (3 puntos)',false,false,true),
(46,'pantorrillas',1,0,'Gastrocnemio, ordeñe general',false,false,false),
(47,'pantorrillas',2,3,'Ordeñe, más tiempo',false,false,false),
(48,'pantorrillas',3,7,'Gastrocnemio interno',false,true,false),
(49,'pantorrillas',4,14,'Sóleo (más profundo)',true,true,false),
(50,'pantorrillas',5,21,'Rutina completa (3 puntos)',false,false,true),
(51,'planta_pie',1,0,'Talón hacia dedos',false,false,false),
(52,'planta_pie',2,3,'Talón hacia dedos, más tiempo',false,false,false),
(53,'planta_pie',3,7,'Centro del arco',false,true,false),
(54,'planta_pie',4,14,'Combinado con pantorrilla',true,true,false),
(55,'planta_pie',5,21,'Rutina completa (pie + pantorrilla)',false,false,true),
(56,'antebrazo',1,0,'Extensores y flexores, general',false,false,false),
(57,'antebrazo',2,3,'Extensores y flexores, más tiempo',false,false,false),
(58,'antebrazo',3,7,'Codo externo ("codo de tenista")',false,true,false),
(59,'antebrazo',4,14,'Codo interno ("codo de golfista")',true,true,false),
(60,'antebrazo',5,21,'Rutina completa (4 puntos)',false,false,true),
(61,'mano_muneca',1,0,'Palma general',false,false,false),
(62,'mano_muneca',2,3,'Palma, más tiempo',false,false,false),
(63,'mano_muneca',3,7,'Base del pulgar',false,true,false),
(64,'mano_muneca',4,14,'Entre los huesos de los dedos',true,true,false),
(65,'mano_muneca',5,21,'Rutina completa (mano y muñeca)',false,false,true),
(66,'pectorales',1,0,'Amasamiento general',false,false,false),
(67,'pectorales',2,3,'Amasamiento, más tiempo',false,false,false),
(68,'pectorales',3,7,'Porción clavicular (parte alta)',false,true,false),
(69,'pectorales',4,14,'Pectoral menor (más profundo)',true,true,false),
(70,'pectorales',5,21,'Rutina completa (3 puntos)',false,false,true),
(71,'abdomen',1,0,'Círculos generales',false,false,false),
(72,'abdomen',2,3,'Círculos, más tiempo',false,false,false),
(73,'abdomen',3,7,'Debajo del esternón',false,true,false),
(74,'abdomen',4,14,'Debajo del ombligo',true,true,false),
(75,'abdomen',5,21,'Rutina completa (3 puntos)',false,false,true);

select setval('public.niveles_zona_id_seq', 75);
