-- Bloque 2.2 — pasos_zona para nivel_id 1 a 40 (trapecio..lumbar)
insert into public.pasos_zona (nivel_id, orden, titulo, detalle, segundos) values
(1,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(1,2,'Ubicar el punto','Sentada, con los brazos relajados, coloca las yemas de los dedos entre el cuello y el hombro. Este punto suele generar dolor referido hacia la sien o detrás del ojo.',20),
(1,3,'Presión en círculos','Presiona firme, en círculos pequeños, sobre el punto más tenso.',30),
(1,4,'Estiramiento de cierre','Lleva la oreja hacia el hombro (sin subir el hombro) y sostén.',20),
(2,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(2,2,'Postura','Sentada, inclina la cabeza levemente hacia el lado contrario al que vas a trabajar, para exponer mejor el borde del músculo.',20),
(2,3,'Presión en el borde','Con las yemas de los dedos, presiona en círculos pequeños sobre el borde lateral del trapecio, cerca del cuello. Este punto suele referir dolor hacia la mandíbula y la oreja.',45),
(2,4,'Estiramiento de cierre','Lleva la oreja hacia el hombro contrario y sostén.',20),
(3,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(3,2,'Postura','Sentada, lleva el brazo del lado a trabajar cruzado hacia el pecho, para separar el omóplato y exponer el trapecio medio.',15),
(3,3,'Presión sostenida','Con los dedos de la otra mano, presiona el punto entre los omóplatos. Suele generar una sensación de ardor en esa zona media de la espalda.',60),
(3,4,'Soltar despacio','Suelta la presión lentamente y respira hondo dos veces.',20),
(4,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(4,2,'Postura','Acostada boca abajo o sentada inclinada hacia adelante, con el brazo relajado colgando, para acceder a la parte más baja del trapecio.',15),
(4,3,'Presión profunda','Nivel avanzado: presiona el punto más bajo, cerca del borde interno del omóplato, con presión más sostenida y profunda. Baja la intensidad de inmediato si duele demasiado.',90),
(4,4,'Estiramiento de cierre','Lleva la oreja hacia el hombro contrario y sostén.',20),
(5,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(5,2,'Punto básico','Yemas de los dedos entre cuello y hombro, presión en círculos.',60),
(5,3,'Borde lateral','Presión en círculos sobre el borde lateral del trapecio.',60),
(5,4,'Punto medio','Presión sostenida en el punto entre los omóplatos.',60),
(5,5,'Punto profundo','Presión más profunda y sostenida en la parte baja del trapecio.',60),
(5,6,'Estiramiento de cierre','Lleva la oreja hacia cada hombro y sostén, respirando lento.',30),
(6,1,'Calentamiento','Con las yemas de los dedos, desliza suavemente por toda la nuca en movimientos largos y livianos, sin presionar fuerte todavía.',20),
(6,2,'Ubicar el borde óseo','Busca con los dedos el borde justo donde termina el cráneo y empieza el cuello, a los costados de la columna.',20),
(6,3,'Presión sostenida con los dedos','Presiona sosteniendo con las yemas de los dedos, moviendo la cabeza suavemente en ''sí'' y ''no'' para encontrar el punto exacto.',60),
(6,4,'Cierre con las palmas','Con las palmas de ambas manos, envuelve la base del cráneo y sostén una presión suave y constante, como un pequeño abrazo.',20),
(7,1,'Calentamiento','Con las yemas de los dedos, desliza suavemente por toda la nuca.',20),
(7,2,'Ubicar el borde óseo','Vuelve al borde donde termina el cráneo, esta vez sosteniendo un poco más de tiempo en cada punto.',20),
(7,3,'Presión sostenida','Presiona con las yemas de los dedos, un poco más firme que la vez anterior, moviendo la cabeza suavemente.',75),
(7,4,'Cierre con las palmas','Envuelve la base del cráneo con las palmas y sostén.',20),
(8,1,'Calentamiento','Desliza suavemente por toda la nuca con las yemas de los dedos.',20),
(8,2,'Ubicar el punto lateral','Busca un poco más hacia el lado, cerca de la base del cráneo. Este punto suele referir dolor hacia la sien del mismo lado.',20),
(8,3,'Presión sostenida','Sostén la presión con las yemas de los dedos, respirando lento.',60),
(8,4,'Cierre','Envuelve la base del cráneo con las palmas y suelta despacio.',20),
(9,1,'Calentamiento','Desliza suavemente por toda la nuca.',20),
(9,2,'Ubicar el mismo punto lateral','Vuelve al punto lateral del nivel anterior.',15),
(9,3,'Presión profunda y sostenida','Nivel avanzado: presiona más profundo y sostén más tiempo. Baja la intensidad si sientes mareo o dolor que se dispara.',90),
(9,4,'Cierre con las palmas','Envuelve la base del cráneo y sostén, respirando hondo.',20),
(10,1,'Calentamiento','Desliza suavemente por toda la nuca.',20),
(10,2,'Lado 1','Presión sostenida en el borde óseo y el punto lateral de un lado.',75),
(10,3,'Lado 2','Repite del otro lado.',75),
(10,4,'Estiramiento de cierre','Envuelve la base del cráneo con ambas palmas y sostén, respirando lento.',30),
(11,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(11,2,'Ubicar el músculo temporal','Coloca las yemas de los dedos por encima de la oreja, en la sien.',15),
(11,3,'Círculos lentos','Presión circular lenta desde la línea del cabello hacia adelante, hasta la esquina externa del ojo.',60),
(11,4,'Combinar con mandíbula','Este trabajo es más efectivo si se combina con el automasaje de mandíbula.',30),
(12,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(12,2,'Ubicar el músculo temporal','Coloca las yemas de los dedos por encima de la oreja.',15),
(12,3,'Círculos con más presión','Repite el recorrido desde la línea del cabello hasta el ojo, con un poco más de presión.',75),
(12,4,'Cierre','Presión suave y sostenida en el punto más tenso.',20),
(13,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(13,2,'Ubicar el punto posterior','Busca con los dedos la parte más posterior del músculo temporal, cerca de la línea del cabello por encima de la oreja.',20),
(13,3,'Presión circular','Círculos suaves y controlados sobre ese punto.',60),
(13,4,'Cierre','Suelta despacio y respira hondo.',20),
(14,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(14,2,'Sien','Presión circular en el punto posterior de la sien.',45),
(14,3,'Masetero (mandíbula)','Nivel avanzado: combina con presión en el masetero (delante de la oreja), ya que ambos músculos suelen trabajar juntos en el bruxismo.',60),
(14,4,'Cierre','Presión suave final en ambos puntos.',20),
(15,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(15,2,'Sien completa','Círculos desde la línea del cabello hasta el ojo, y en el punto posterior.',75),
(15,3,'Mandíbula','Presión circular en el masetero.',60),
(15,4,'Cierre','Presión suave y sostenida en ambos puntos, respirando lento.',20),
(16,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(16,2,'Ubicar el masetero','Coloca los dedos delante de las orejas, donde sientes movimiento al apretar los dientes.',15),
(16,3,'Presión circular','Círculos suaves y controlados sobre el masetero.',60),
(16,4,'Zona baja de la mandíbula','Con la boca relajada, presiona suavemente con el pulgar debajo del hueso de la mandíbula.',30),
(17,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(17,2,'Ubicar el masetero','Coloca los dedos delante de las orejas.',15),
(17,3,'Presión circular sostenida','Círculos suaves, sosteniendo un poco más en el punto más tenso.',75),
(17,4,'Cierre','Presión suave debajo del hueso de la mandíbula.',20),
(18,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(18,2,'Ubicar el punto profundo','Busca un poco más adentro y abajo del ángulo de la mandíbula. Puede referir dolor hacia el oído y los dientes.',20),
(18,3,'Presión sostenida','Presiona con el pulgar o las yemas de los dedos, con calma.',60),
(18,4,'Cierre','Suelta despacio.',20),
(19,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(19,2,'Ubicar el punto profundo','Vuelve al punto profundo del nivel anterior.',15),
(19,3,'Presión + movimiento suave','Nivel avanzado: sostén la presión mientras abres y cierras suavemente la boca unas cuantas veces.',75),
(19,4,'Cierre','Presión suave final.',20),
(20,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(20,2,'Masetero superficial','Círculos suaves delante de la oreja.',45),
(20,3,'Masetero profundo','Presión sostenida más adentro y abajo del ángulo mandibular.',60),
(20,4,'Sien','Círculos suaves en la sien.',45),
(20,5,'Cierre','Presión suave final en los tres puntos.',20),
(21,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(21,2,'Ubicar el músculo','Con la mano contraria, ubica la parte externa del hombro.',20),
(21,3,'Presión lenta y profunda','Desliza lento a lo largo de las fibras, de arriba hacia abajo.',90),
(21,4,'Estiramiento de cierre','Lleva el brazo cruzado hacia el pecho, suave.',20),
(22,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(22,2,'Ubicar el músculo','Con la mano contraria, ubica la parte externa y media del hombro.',20),
(22,3,'Presión lenta y profunda','Desliza lento a lo largo de las fibras, sosteniendo un poco más en el punto más tenso.',100),
(22,4,'Estiramiento de cierre','Lleva el brazo cruzado hacia el pecho.',20),
(23,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(23,2,'Ubicar la parte delantera','Con la mano contraria, ubica la parte de adelante del hombro. Suele doler al levantar el brazo hacia adelante.',20),
(23,3,'Presión lenta','Desliza lento sobre esas fibras.',60),
(23,4,'Cierre','Lleva el brazo cruzado hacia el pecho y sostén.',20),
(24,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(24,2,'Postura','Lleva el brazo cruzado hacia el pecho y trabaja la parte de atrás del hombro con la mano contraria.',15),
(24,3,'Presión profunda','Nivel avanzado: presión más sostenida sobre las fibras posteriores, más difíciles de alcanzar.',75),
(24,4,'Cierre','Suelta despacio.',20),
(25,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',20),
(25,2,'Porción externa/media','Presión lenta de arriba hacia abajo.',60),
(25,3,'Porción anterior','Presión lenta en la parte delantera.',45),
(25,4,'Porción posterior','Presión en la parte de atrás del hombro.',60),
(25,5,'Estiramiento de cierre','Brazo cruzado hacia el pecho, sostén respirando lento.',20),
(26,1,'Calentamiento','Con la palma de la mano contraria, desliza suavemente sobre el omóplato en movimientos largos, sin presionar fuerte todavía.',20),
(26,2,'Ubicar con los dedos','Lleva la mano contraria por encima del hombro o rodeando el costado, y busca con los dedos el borde interno del omóplato.',20),
(26,3,'Presión con los dedos','Presiona con las yemas de los dedos en círculos pequeños sobre el punto más tenso.',45),
(26,4,'Estiramiento de cierre','Lleva ese brazo cruzado hacia el pecho, sostenido con la otra mano, para estirar suavemente la zona.',20),
(27,1,'Calentamiento','Desliza suavemente sobre el omóplato con la palma de la mano.',20),
(27,2,'Ubicar con los dedos','Busca el borde interno del omóplato.',20),
(27,3,'Presión sostenida','Presiona con los dedos, sosteniendo un poco más de tiempo en el punto más tenso.',60),
(27,4,'Cierre','Brazo cruzado hacia el pecho, sostén.',20),
(28,1,'Calentamiento','Desliza suavemente sobre el omóplato.',20),
(28,2,'Ubicar el punto superior','Busca la parte superior del omóplato, cerca de donde el romboides menor se une a la columna.',20),
(28,3,'Presión con los dedos','Círculos pequeños y sostenidos sobre ese punto.',50),
(28,4,'Cierre','Brazo cruzado hacia el pecho.',20),
(29,1,'Calentamiento','Desliza suavemente desde el omóplato hacia el cuello.',20),
(29,2,'Ubicar el elevador','Busca justo arriba del omóplato, hacia el cuello — casi siempre acompaña la tensión de romboides.',20),
(29,3,'Presión profunda','Nivel avanzado: presión sostenida y un poco más profunda en este punto.',75),
(29,4,'Cierre','Estiramiento suave llevando la oreja hacia el hombro contrario.',20),
(30,1,'Calentamiento','Desliza suavemente sobre toda la zona.',20),
(30,2,'Borde interno + superior','Presión con los dedos en ambos puntos del omóplato.',70),
(30,3,'Elevador de la escápula','Presión sostenida hacia el cuello.',60),
(30,4,'Estiramiento de cierre','Brazo cruzado hacia el pecho y oreja hacia el hombro contrario.',30),
(31,1,'Calentamiento','Con la palma de la mano, desliza suavemente sobre la zona en movimientos largos, sin presionar fuerte todavía.',20),
(31,2,'Posición','Acostada boca arriba o sentada, lleva la mano por encima del hombro contrario hacia la zona alta de la espalda.',15),
(31,3,'Presión con los nudillos','Con los nudillos o las yemas de los dedos, presiona en círculos pequeños buscando el punto más tenso.',45),
(31,4,'Sostener','Mantén la presión con los dedos, respirando lento.',30),
(32,1,'Calentamiento','Desliza suavemente sobre la zona con la palma.',20),
(32,2,'Posición','Lleva la mano hacia la zona alta de la espalda.',15),
(32,3,'Presión con los nudillos','Círculos pequeños, sosteniendo un poco más en el punto más tenso.',60),
(32,4,'Sostener','Respira lento manteniendo la presión.',30),
(33,1,'Calentamiento','Desliza suavemente sobre la zona.',20),
(33,2,'Ubicar el borde externo','Busca el borde externo del dorsal ancho, cerca de la axila. Puede referir dolor hacia la parte interna del brazo.',20),
(33,3,'Presión con los dedos','Círculos suaves y sostenidos sobre ese punto.',50),
(33,4,'Cierre','Suelta despacio.',20),
(34,1,'Calentamiento','Desliza suavemente sobre la zona.',20),
(34,2,'Ubicar el punto','Busca el ángulo inferior del omóplato (la punta de abajo).',20),
(34,3,'Presión profunda','Nivel avanzado: con los nudillos, presión más profunda y sostenida en este punto.',75),
(34,4,'Cierre','Suelta despacio, respirando hondo.',20),
(35,1,'Calentamiento','Desliza suavemente sobre toda la zona.',20),
(35,2,'Punto medio','Presión con nudillos en la zona alta de la espalda.',50),
(35,3,'Borde externo','Presión con los dedos cerca de la axila.',50),
(35,4,'Ángulo inferior','Presión con nudillos en el ángulo inferior del omóplato.',50),
(35,5,'Cierre','Respira lento manteniendo una presión suave final.',20),
(36,1,'Calentamiento','Con las palmas de ambas manos, desliza suavemente sobre la zona lumbar en movimientos largos, sin presionar fuerte todavía.',20),
(36,2,'Posición inicial','Acostada boca arriba, rodillas flexionadas, pies apoyados en el piso.',15),
(36,3,'Formar los puños','Cierra ambas manos en puño, con los nudillos hacia arriba, y colócalos debajo de la zona lumbar, uno a cada lado de la columna.',20),
(36,4,'Dejar caer el peso','Deja caer suavemente el peso de tu cuerpo sobre los puños y sostén la presión respirando hondo.',90),
(37,1,'Calentamiento','Desliza suavemente con las palmas sobre la zona lumbar.',20),
(37,2,'Posición inicial','Acostada boca arriba, rodillas flexionadas.',15),
(37,3,'Puños bajo la zona lumbar','Coloca los puños a los lados de la columna y deja caer el peso.',100),
(37,4,'Respirar','Sostén respirando hondo, sin prisa.',20),
(38,1,'Calentamiento','Desliza suavemente sobre la zona lumbar.',20),
(38,2,'Ubicar el punto lateral','Busca un poco más hacia el lado, cerca de la cresta de la cadera (cuadrado lumbar). Puede referir dolor hacia el glúteo.',20),
(38,3,'Presión con el puño','Coloca el puño en ese punto y deja caer el peso con calma.',60),
(38,4,'Cierre','Suelta despacio.',20),
(39,1,'Calentamiento','Desliza suavemente sobre la zona.',20),
(39,2,'Ubicar el punto','Vuelve al punto cerca de la cresta de la cadera.',15),
(39,3,'Presión sostenida y profunda','Nivel avanzado: deja caer más peso y sostén más tiempo. Baja la intensidad si el dolor se dispara hacia la pierna.',90),
(39,4,'Cierre','Suelta despacio, respirando hondo.',20),
(40,1,'Calentamiento','Desliza suavemente sobre toda la zona lumbar.',20),
(40,2,'Lado 1 — columna y cadera','Puños a los lados de la columna y en el punto cerca de la cadera.',90),
(40,3,'Lado 2 — columna y cadera','Repite del otro lado.',90),
(40,4,'Cierre','Respira lento, sin presión, unos segundos más.',20);
