insert into public.pasos_zona (nivel_id, orden, titulo, detalle, segundos) values
(41,1,'Calentamiento','Con la palma de la mano, desliza suavemente sobre todo el glúteo en movimientos largos, sin presionar fuerte todavía.',25),
(41,2,'Posición','Sentada, cruza el tobillo de la pierna a trabajar sobre la rodilla contraria, dejando el glúteo más accesible.',20),
(41,3,'Presión con el puño','Cierra la mano en puño y presiona con los nudillos en el centro del glúteo, buscando el punto más sensible.',45),
(41,4,'Sostener','Mantén la presión con el puño y respira hondo hasta sentir que afloja.',30),
(42,1,'Calentamiento','Desliza suavemente sobre el glúteo.',25),
(42,2,'Posición','Cruza el tobillo sobre la rodilla contraria.',20),
(42,3,'Presión con el puño','Presiona en el centro del glúteo, sosteniendo un poco más.',55),
(42,4,'Sostener','Respira hondo manteniendo la presión.',30),
(43,1,'Calentamiento','Desliza suavemente sobre el glúteo.',25),
(43,2,'Ubicar el punto alto','Busca un poco más arriba y hacia afuera, cerca del hueso de la cadera. Suele referir dolor a lo largo de la cresta de la cadera y hacia el sacro.',25),
(43,3,'Presión con los nudillos','Presiona con calma en ese punto.',50),
(43,4,'Cierre','Suelta despacio.',25),
(44,1,'Calentamiento','Desliza suavemente sobre el glúteo.',25),
(44,2,'Ubicar el punto','Busca un poco más abajo del punto anterior. Puede referir hacia el centro del glúteo y a veces hacia el muslo.',25),
(44,3,'Presión profunda','Nivel avanzado: presión más profunda y sostenida con el puño.',75),
(44,4,'Cierre','Suelta despacio, respirando hondo.',25),
(45,1,'Calentamiento','Desliza suavemente sobre todo el glúteo.',25),
(45,2,'Piriforme central','Presión con el puño en el centro del glúteo.',50),
(45,3,'Glúteo medio, punto alto','Presión con nudillos cerca del hueso de la cadera.',50),
(45,4,'Glúteo medio, punto medio','Presión con el puño, un poco más abajo.',50),
(45,5,'Cierre','Respira lento, soltando toda la presión.',25),
(46,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(46,2,'Posición','Sentado, con la pierna estirada.',15),
(46,3,'Ordeñar hacia arriba','Con ambas manos, desliza desde el tobillo hacia la rodilla, siempre hacia arriba.',90),
(46,4,'Cierre en pared','Eleva las piernas apoyadas en la pared, moviendo los pies suavemente.',120),
(47,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(47,2,'Posición','Sentado, con la pierna estirada.',15),
(47,3,'Ordeñar hacia arriba','Desliza desde el tobillo hacia la rodilla, sosteniendo un poco más en los puntos tensos.',110),
(47,4,'Cierre en pared','Eleva las piernas apoyadas en la pared.',120),
(48,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(48,2,'Ubicar el lado interno','Busca el lado interno de la pantorrilla. Puede referir hacia el arco del pie.',25),
(48,3,'Presión con los dedos','Presiona en círculos pequeños a lo largo del lado interno.',60),
(48,4,'Cierre','Ordeña suavemente hacia arriba para cerrar.',25),
(49,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(49,2,'Ubicar el sóleo','Busca más abajo y profundo, cerca del tendón de Aquiles. Puede referir dolor hacia el talón.',25),
(49,3,'Presión profunda','Nivel avanzado: presión sostenida y más profunda en este punto.',75),
(49,4,'Cierre','Ordeña suavemente hacia arriba.',25),
(50,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(50,2,'Ordeñe general','Desde el tobillo hacia la rodilla.',60),
(50,3,'Gastrocnemio interno','Presión en el lado interno de la pantorrilla.',50),
(50,4,'Sóleo','Presión profunda cerca del tendón de Aquiles.',50),
(50,5,'Cierre en pared','Eleva las piernas apoyadas en la pared.',90),
(51,1,'Calentamiento','Con las palmas de ambas manos, desliza suavemente por toda la planta del pie, sin presionar fuerte todavía.',25),
(51,2,'Posición','Sentada, cruza el pie a trabajar sobre la rodilla contraria para tener buen acceso.',15),
(51,3,'Presión con los pulgares','Con ambos pulgares, presiona en círculos pequeños desde el talón hacia los dedos.',60),
(51,4,'Puntos sensibles','Detente 20 a 30 segundos en los puntos más sensibles.',30),
(52,1,'Calentamiento','Desliza suavemente por toda la planta con las palmas.',25),
(52,2,'Posición','Cruza el pie sobre la rodilla contraria.',15),
(52,3,'Presión con los pulgares','Desde el talón hacia los dedos, sosteniendo un poco más en cada punto.',75),
(52,4,'Puntos sensibles','Detente en los puntos más sensibles.',30),
(53,1,'Calentamiento','Desliza suavemente por la planta del pie.',25),
(53,2,'Ubicar el centro del arco','Busca con los pulgares el punto central del arco del pie.',20),
(53,3,'Presión sostenida','Presiona con calma en ese punto.',60),
(53,4,'Cierre','Suelta despacio.',25),
(54,1,'Calentamiento','Desliza suavemente por la planta del pie y la pantorrilla.',25),
(54,2,'Planta','Presión sostenida en el centro del arco.',45),
(54,3,'Sóleo (pantorrilla)','Nivel avanzado: combina con presión profunda en el sóleo (pantorrilla) — el dolor de planta muchas veces viene referido desde ahí.',60),
(54,4,'Cierre','Ordeña suavemente hacia arriba.',25),
(55,1,'Calentamiento','Desliza suavemente por pie y pantorrilla.',25),
(55,2,'Talón a dedos','Presión con los pulgares.',50),
(55,3,'Centro del arco','Presión sostenida.',40),
(55,4,'Pantorrilla (sóleo)','Presión profunda cerca del tendón de Aquiles.',50),
(55,5,'Cierre','Ordeña suavemente hacia arriba para terminar.',25),
(56,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(56,2,'Extensores','Antebrazo apoyado en la mesa, palma hacia abajo, presión suave en círculos desde la muñeca hasta el codo.',60),
(56,3,'Flexores','Antebrazo sobre la mesa, palma hacia arriba, mismo círculo.',60),
(56,4,'Estiramiento','Brazo extendido, flexiona la muñeca hacia abajo y luego hacia arriba.',30),
(57,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(57,2,'Extensores','Presión en círculos desde la muñeca hasta el codo, sosteniendo un poco más.',75),
(57,3,'Flexores','Mismo recorrido del lado de la palma hacia arriba.',75),
(57,4,'Estiramiento','Flexiona la muñeca hacia abajo y arriba.',30),
(58,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(58,2,'Ubicar el punto','Busca cerca del codo, del lado externo del antebrazo.',20),
(58,3,'Presión con los dedos','Círculos suaves y sostenidos en ese punto.',60),
(58,4,'Cierre','Estiramiento suave de la muñeca hacia abajo.',25),
(59,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(59,2,'Ubicar el punto','Busca cerca del codo, del lado interno del antebrazo.',20),
(59,3,'Presión profunda','Nivel avanzado: presión más profunda y sostenida en este punto.',75),
(59,4,'Cierre','Estiramiento suave de la muñeca hacia arriba.',25),
(60,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(60,2,'Extensores','Círculos desde la muñeca hasta el codo.',45),
(60,3,'Flexores','Mismo recorrido del lado de la palma.',45),
(60,4,'Codo externo','Presión sostenida cerca del codo, lado externo.',40),
(60,5,'Codo interno','Presión sostenida cerca del codo, lado interno.',40),
(60,6,'Estiramiento de cierre','Flexiona la muñeca hacia abajo y hacia arriba.',30),
(61,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(61,2,'Palma','Con el pulgar de la otra mano, círculos desde el centro de la palma hacia los dedos.',90),
(61,3,'Entre los dedos','Presión suave en la base de cada dedo.',30),
(61,4,'Muñeca','Círculos suaves alrededor de la muñeca.',30),
(62,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(62,2,'Palma','Círculos desde el centro de la palma hacia los dedos, sosteniendo un poco más.',100),
(62,3,'Entre los dedos','Presión suave en la base de cada dedo.',30),
(62,4,'Muñeca','Círculos suaves alrededor de la muñeca.',30),
(63,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(63,2,'Ubicar el punto','Busca con el pulgar de la otra mano la base de tu propio pulgar.',20),
(63,3,'Presión sostenida','Círculos suaves y sostenidos en ese punto.',60),
(63,4,'Cierre','Círculos suaves alrededor de la muñeca.',25),
(64,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(64,2,'Ubicar los espacios','Busca los espacios entre los huesos de los dedos, en el dorso de la mano.',20),
(64,3,'Presión fina','Nivel avanzado: presión fina y controlada en cada espacio, con el pulgar o un dedo.',75),
(64,4,'Cierre','Círculos suaves en la muñeca.',25),
(65,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(65,2,'Palma','Círculos desde el centro hacia los dedos.',60),
(65,3,'Base del pulgar','Presión sostenida en ese punto.',40),
(65,4,'Espacios entre los dedos','Presión fina en cada espacio.',50),
(65,5,'Muñeca','Círculos suaves de cierre.',30),
(66,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(66,2,'Posición','Sentado o de pie, con la mano contraria al lado a masajear.',15),
(66,3,'Amasar','Desde el esternón hacia el costado, con amasamiento suave.',60),
(66,4,'Estiramiento','Apoya el antebrazo en una esquina o marco de puerta y rota el tronco hacia el lado contrario.',25),
(67,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(67,2,'Posición','Mano contraria al lado a masajear.',15),
(67,3,'Amasar','Desde el esternón hacia el costado, sosteniendo un poco más en los puntos tensos.',75),
(67,4,'Estiramiento','Antebrazo en el marco de una puerta, rota el tronco.',25),
(68,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(68,2,'Ubicar el punto','Busca la parte alta del pecho, cerca de la clavícula. Suele referir dolor hacia el hombro.',20),
(68,3,'Presión suave','Círculos suaves y sostenidos en ese punto.',55),
(68,4,'Cierre','Estiramiento en el marco de una puerta.',25),
(69,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(69,2,'Ubicar el punto','Busca debajo del pectoral mayor, cerca de la axila (pectoral menor). Zona sensible.',20),
(69,3,'Presión suave y gradual','Nivel avanzado: precaución — presión suave y gradual, nunca brusca, en este punto.',60),
(69,4,'Cierre','Estiramiento suave en el marco de una puerta.',25),
(70,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(70,2,'Amasamiento general','Desde el esternón hacia el costado.',45),
(70,3,'Porción clavicular','Presión suave cerca de la clavícula.',40),
(70,4,'Pectoral menor','Presión suave y gradual cerca de la axila.',45),
(70,5,'Estiramiento de cierre','Antebrazo en el marco de una puerta, rota el tronco.',25),
(71,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(71,2,'Posición','Acostado boca arriba, rodillas flexionadas, manos relajadas sobre el abdomen.',20),
(71,3,'Movimiento circular','Círculos suaves con las yemas de los dedos en sentido de las agujas del reloj.',90),
(71,4,'Respiración','Acompaña cada movimiento con una respiración profunda y lenta.',30),
(72,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(72,2,'Posición','Rodillas flexionadas, manos relajadas sobre el abdomen.',20),
(72,3,'Movimiento circular','Círculos suaves en sentido de las agujas del reloj, un poco más lentos.',105),
(72,4,'Respiración','Respiración profunda y lenta.',30),
(73,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(73,2,'Ubicar el punto','Busca justo debajo del esternón. Puede relacionarse con sensación de pesadez similar a la digestiva.',20),
(73,3,'Presión suave','Círculos muy suaves en ese punto, nunca profundos.',55),
(73,4,'Respiración','Respira lento y profundo.',25),
(74,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(74,2,'Ubicar el punto','Busca un poco debajo del ombligo.',20),
(74,3,'Presión suave y controlada','Nivel avanzado en tiempo, pero la presión sigue siendo suave y controlada — nunca profunda ni brusca en esta zona.',60),
(74,4,'Respiración','Respira lento y profundo.',25),
(75,1,'Calentamiento','Con la palma o las yemas de los dedos, desliza suavemente sobre toda la zona en movimientos largos y livianos, sin presionar fuerte todavía — esto prepara el tejido y hace la técnica siguiente más efectiva y menos molesta.',25),
(75,2,'Círculos generales','En sentido de las agujas del reloj.',60),
(75,3,'Debajo del esternón','Círculos muy suaves.',40),
(75,4,'Debajo del ombligo','Presión suave y controlada.',40),
(75,5,'Respiración de cierre','Respira lento y profundo, manos quietas sobre el abdomen.',30);
